import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { createServer } from 'vite';
const server=await createServer({server:{host:'127.0.0.1',port:5178,strictPort:true}});await server.listen();
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{
 const context=await browser.newContext();let status='unavailable';const mutations=[];
 await context.route('**/api/**',route=>{const url=new URL(route.request().url());if(!url.pathname.startsWith('/api/'))return route.continue();if(route.request().method()!=='GET')mutations.push(url.pathname);if(url.pathname==='/api/recovery/status')return route.fulfill({status:status==='unavailable'?503:200,json:{safeMode:true,requiresReview:true,automaticResume:false}});return route.fulfill({json:url.pathname==='/api/auth/me'?{user:{username:'admin',role:'admin'}}:{clusters:[],oidc:{enabled:false}}});});
 const page=await context.newPage();page.on('pageerror',e=>console.log('PAGEERROR',e.message));await page.goto('http://127.0.0.1:5178/');await page.getByText('Не удалось проверить режим восстановления.',{exact:false}).waitFor();assert.equal(await page.locator('.console-app').count(),0);
 status='safe';await page.getByRole('button',{name:'Повторить',exact:true}).click();await page.getByText('Безопасный режим после восстановления',{exact:true}).waitFor();assert.equal(await page.locator('.recovery-banner button').count(),0);
 await page.evaluate(()=>localStorage.setItem('talosdeck.console.language','en'));await page.reload();await page.getByText('Recovery safe mode',{exact:true}).waitFor();await page.getByText('Nothing resumes automatically.',{exact:false}).waitFor();assert.deepEqual(mutations,[]);await context.close();
 const jc=await browser.newContext();const id='e5a0d9ea-9b91-45c1-8f54-472eeb8c12d2';let calls=0;
 const job={id,request:{kind:'cluster-create'},user:'admin',status:'interrupted',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),step:'create-vm',reviewed:false,reconciliationOutcome:'UNKNOWN',intents:[{id:'create:machine',action:'create',executorEpoch:42,outcome:'UNKNOWN',identity:{providerId:'provider',resourceId:'pve/117',generation:'machine',ownerId:'cluster'}}]};
 await jc.route('**/fixture',r=>r.fulfill({contentType:'text/html',body:'<html><body><div id="fixture"></div></body></html>'}));
 await jc.route('**/api/**',r=>{const req=r.request(),path=new URL(req.url()).pathname;if(!path.startsWith('/api/'))return r.continue();if(req.method()==='POST'){assert.equal(path,`/api/provision/jobs/${id}/reconcile`);assert.equal(req.postData(),null);calls++;job.reconciliationOutcome='succeeded';job.intents[0].outcome='succeeded';job.intents[0].evidence={state:'exists',observedAt:new Date().toISOString(),source:'provider_ownership_verified'};return r.fulfill({json:job});}return r.fulfill({json:path.endsWith('/jobs')?[job]:job});});
 const jp=await jc.newPage();await jp.goto('http://127.0.0.1:5178/fixture');
 await jp.evaluate(async()=>{const {createApp}=await import('/node_modules/.vite/deps/vue.js');const {default:JobsView}=await import('/src/console/JobsView.vue');const api=await import('/src/api/index.ts');const recovery=await import('/src/console/recovery.ts');api.isAuthenticated.value=true;api.currentUser.value={username:'admin',role:'admin'};recovery.recoveryState.value='safe';createApp(JobsView,{mode:'jobs',global:true}).mount('#fixture');});
 await jp.getByRole('button',{name:'Сверить с провайдером',exact:true}).click();await jp.getByText('Подтверждение результата',{exact:true}).waitFor();assert.equal(calls,1);assert.equal(await jp.getByRole('button',{name:'Проверить прерывание',exact:true}).count(),0);await jp.locator('.intent-evidence summary').click();await jp.getByText('Проверена принадлежность машины',{exact:true}).waitFor();await jp.evaluate(async()=>{const api=await import('/src/api/index.ts');api.currentUser.value={username:'viewer',role:'viewer'};});await jp.getByRole('button',{name:'Сверить с провайдером',exact:true}).waitFor({state:'hidden'});await jc.close();console.log('Recovery UI smoke passed');
}finally{await browser.close();await server.close();}
