{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "talosdeck.fullname" . }}-data
  labels:
    {{- include "talosdeck.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and (not .Values.encryption.existingSecret) (not .Values.encryption.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "talosdeck.fullname" . }}-keys
  labels:
    {{- include "talosdeck.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.encryption.storageClass }}
  storageClassName: {{ .Values.encryption.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.encryption.size }}
{{- end }}
