<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { request, post } from './client';
import { t } from './i18n';
import { canOperate } from './permissions';
import { notificationTime, notificationDuration, notificationLabel, type AlertRecord, type AlertSnapshot, type Silence } from './notifications';
import ResourceTable from './ResourceTable.vue';
import Modal from './Modal.vue';
import DeliveryHistory from './DeliveryHistory.vue';
const emit=defineEmits<{node:[name:string];logs:[name:string]}>();
const report=ref<AlertSnapshot|null>(null),alerts=ref<AlertRecord[]>([]),silences=ref<Silence[]>([]),error=ref(''),busy=ref(false),tab=ref('alerts'),state=ref('active'),severity=ref(''),selected=ref<AlertRecord|null>(null),nextOffset=ref<number|null>(null),total=ref(0),silencedOnly=ref(false),silenceOpen=ref(false),cancelSilence=ref<Silence|null>(null);
const form=ref({ruleId:'',node:'',severity:'',hours:1,reason:''});
let live=true;
const rows=computed(()=>alerts.value.filter(a=>!silencedOnly.value||a.silencedUntil&&Date.parse(a.silencedUntil)>Date.now()).map(a=>({...a,severityLabel:notificationLabel(a.severity),stateLabel:a.event?t('Событие'):notificationLabel(a.state),duration:notificationDuration(a.firstSeen,a.resolvedAt),freshness:notificationLabel(a.observation),silence:a.silencedUntil?notificationTime(a.silencedUntil):'—'})));
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){if(live)error.value=e instanceof Error?e.message:String(e);}finally{if(live)busy.value=false;}}
async function load(more=false){await run(async()=>{const result=await request(`/alerts?state=${state.value}&severity=${severity.value}&offset=${more?nextOffset.value||0:0}&limit=100`);if(live){report.value=result;alerts.value=more?[...alerts.value,...result.alerts]:result.alerts;nextOffset.value=result.nextOffset??null;total.value=result.total??result.alerts.length;}});}
async function loadSilences(){await run(async()=>{const r=await request('/alerts/silences');if(live)silences.value=r.silences||[];});}
function beginSilence(alert?:AlertRecord){form.value={ruleId:alert?.ruleId||'',node:alert?.node||'',severity:'',hours:1,reason:''};selected.value=null;silenceOpen.value=true;}
async function saveSilence(){await run(async()=>{const now=Date.now();await post('/alerts/silences',{ruleId:form.value.ruleId,node:form.value.node,severity:form.value.severity,reason:form.value.reason,startsAt:new Date(now).toISOString(),endsAt:new Date(now+form.value.hours*3600000).toISOString()});if(live)silenceOpen.value=false;});if(!error.value)await load();}
async function removeSilence(){const id=cancelSilence.value?.id;if(!id)return;await run(async()=>{await request('/alerts/silences/'+encodeURIComponent(id),{method:'DELETE'});if(live)cancelSilence.value=null;});if(!error.value)await loadSilences();}
onMounted(()=>load());onUnmounted(()=>{live=false;});
</script>
<template>
<section class="panel"><header><div><h2>{{ t('Центр оповещений') }}</h2><p>{{ t('Последняя проверка') }}: {{ notificationTime(report?.lastCheckAt) }}</p></div><button v-if="tab!=='deliveries'" :disabled="busy" @click="tab==='silences'?loadSilences():load()">{{ t('Обновить') }}</button></header>
<nav class="section-tabs"><button :disabled="busy" :aria-current="tab==='alerts'?'page':undefined" @click="tab='alerts';load()">{{ t('Оповещения') }}</button><button v-if="canOperate" :disabled="busy" @click="tab='silences';loadSilences()">{{ t('Приостановки') }}</button><button v-if="canOperate" :disabled="busy" @click="tab='deliveries'">{{ t('История доставки') }}</button></nav>
<p v-if="error" class="notice error" role="alert">{{ error }}</p><p v-if="report?.health==='degraded'" class="notice warning">{{ t('Центр оповещений работает с ограничениями. Состояние и доставка могут быть неполными.') }}</p><p v-if="!report?.lastCheckAt||report.lastCheckAt.startsWith('0001-')||report?.health==='unknown'||report?.summary.stale" class="notice warning">{{ t('Часть наблюдений устарела или недоступна. Отсутствие новых сигналов не означает устранение проблемы.') }}</p>
<DeliveryHistory v-if="tab==='deliveries'" />
<template v-else-if="tab==='silences'"><div class="toolbar"><button class="primary" @click="beginSilence()">{{ t('Приостановить оповещения') }}</button></div><ResourceTable :rows="silences.map(s=>({...s,until:notificationTime(s.endsAt)}))" :empty="t('Нет приостановок')" :columns="[{key:'ruleId',title:t('Правило')},{key:'node',title:t('Нода')},{key:'reason',title:t('Причина')},{key:'until',title:t('До')},{key:'createdBy',title:t('Пользователь')}]" @select="cancelSilence=$event" /></template>
<template v-else><div class="summary-strip"><span>{{ t('Активно') }} <strong>{{ report?.summary.active??'—' }}</strong></span><span>{{ t('Критические') }} <strong>{{ report?.summary.critical??'—' }}</strong></span><span>{{ t('Устарело') }} <strong>{{ report?.summary.stale??'—' }}</strong></span><span>{{ t('Приостановлено') }} <strong>{{ report?.summary.silenced??'—' }}</strong></span></div><div class="toolbar"><label>{{ t('Состояние') }}<select :disabled="busy" v-model="state" :aria-label="t('Состояние оповещения')" @change="load()"><option value="active">{{ t('Активно') }}</option><option value="resolved">{{ t('Устранено') }}</option><option value="all">{{ t('Все') }}</option></select></label><label>{{ t('Уровень') }}<select :disabled="busy" v-model="severity" :aria-label="t('Уровень оповещения')" @change="load()"><option value="">{{ t('Все') }}</option><option v-for="value in ['critical','warning','info']" :key="value" :value="value">{{ notificationLabel(value) }}</option></select></label><label><input v-model="silencedOnly" type="checkbox" /> {{ t('Только приостановленные') }}</label></div><div v-if="busy&&!report" class="loading-state">{{ t('Загрузка…') }}</div><ResourceTable v-else :rows="rows" :empty="error?t('Данные недоступны'):t('Нет оповещений по выбранным фильтрам')" :columns="[{key:'title',title:t('Оповещение')},{key:'severityLabel',title:t('Уровень')},{key:'stateLabel',title:t('Состояние')},{key:'node',title:t('Нода')},{key:'duration',title:t('Длительность')},{key:'freshness',title:t('Наблюдение')},{key:'silence',title:t('Приостановлено до')}]" @select="selected=$event" /><div class="toolbar"><span>{{ alerts.length }} / {{ total }}</span><button v-if="nextOffset!==null" :disabled="busy" @click="load(true)">{{ t('Загрузить ещё') }}</button></div></template>
</section>
<Modal v-if="selected" :title="selected.title" @close="selected=null"><div class="summary-strip"><span>{{ selected.event?t('Событие'):notificationLabel(selected.state) }}</span><span>{{ notificationLabel(selected.severity) }}</span><span>{{ notificationLabel(selected.observation) }}</span></div><p class="inspection-copy">{{ selected.details }}</p><dl class="detail-grid"><dt>{{ t('Первое наблюдение') }}</dt><dd>{{ notificationTime(selected.firstSeen) }}</dd><dt>{{ t('Последнее наблюдение') }}</dt><dd>{{ notificationTime(selected.lastSeen) }}</dd><dt>{{ t('Устранено') }}</dt><dd>{{ notificationTime(selected.resolvedAt) }}</dd><dt>{{ t('Длительность') }}</dt><dd>{{ notificationDuration(selected.firstSeen,selected.resolvedAt) }}</dd><dt>{{ t('Правило') }}</dt><dd>{{ selected.ruleId }}</dd><dt>{{ t('Повторения') }}</dt><dd>{{ selected.occurrences }}</dd></dl><h3>{{ t('Рекомендация') }}</h3><p>{{ selected.suggestedAction||'—' }}</p><div class="toolbar"><button v-if="selected.node" @click="emit('node',selected.node);selected=null">{{ t('Открыть ноду') }}</button><button v-if="selected.node" @click="emit('logs',selected.node);selected=null">{{ t('Логи ноды') }}</button><button v-if="canOperate&&selected.state==='active'" @click="beginSilence(selected)">{{ t('Приостановить оповещения') }}</button></div></Modal>
<Modal v-if="silenceOpen" :title="t('Приостановить оповещения')" @close="!busy&&(silenceOpen=false)"><form class="settings-form" @submit.prevent="saveSilence"><p>{{ t('Приостановка отключает доставку совпадающих оповещений, но не скрывает проблему.') }}</p><p v-if="!form.ruleId.trim()&&!form.node.trim()&&!form.severity" class="notice warning">{{ t('Укажите хотя бы одно правило, ноду или уровень.') }}</p><label>{{ t('Правило') }}<input v-model="form.ruleId" /></label><label>{{ t('Нода') }}<input v-model="form.node" /></label><label>{{ t('Уровень') }}<select v-model="form.severity"><option value="">{{ t('Все') }}</option><option v-for="value in ['critical','warning','info']" :key="value">{{ value }}</option></select></label><label>{{ t('Длительность, часы') }}<input v-model.number="form.hours" type="number" min="0.25" step="0.25" max="720" required /></label><label>{{ t('Причина') }}<input v-model="form.reason" required maxlength="500" /></label><p v-if="error" class="notice error" role="alert">{{ error }}</p><button class="primary" :disabled="busy||!form.reason.trim()||(!form.ruleId.trim()&&!form.node.trim()&&!form.severity)">{{ t('Подтвердить приостановку') }}</button></form></Modal>
<Modal v-if="cancelSilence" :title="t('Возобновить оповещения')" @close="cancelSilence=null"><p>{{ cancelSilence.reason }} · {{ notificationTime(cancelSilence.endsAt) }}</p><p>{{ t('Будущие совпадающие оповещения снова смогут отправляться.') }}</p><p v-if="error" class="notice error">{{ error }}</p><button :disabled="busy" @click="removeSilence">{{ t('Подтвердить возобновление') }}</button></Modal>
</template>
