<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted} from 'vue';import {request} from './client';import {t} from './i18n';import {healthLabel,healthExpired,healthNumber,type HealthReport,type HealthCategory,type HealthCheck} from './health';import {certificateDate} from './certificates';import ResourceTable from './ResourceTable.vue';import Modal from './Modal.vue';
const emit=defineEmits<{node:[string];logs:[string];diagnostics:[]}>();
const report=ref<HealthReport|null>(null),busy=ref(false),error=ref(''),category=ref<HealthCategory|null>(null),check=ref<HealthCheck|null>(null),now=ref(Date.now());let live=true,timer:ReturnType<typeof setInterval>|undefined;
const stale=computed(()=>healthExpired(report.value,now.value)),critical=computed(()=>(report.value?.findings||[]).filter(c=>c.state==='critical'));
const rows=computed(()=>(report.value?.categories||[]).map(c=>({...c,label:healthLabel(c.id),result:c.score===null?t('Недостаточно данных'):healthNumber(c.score),coverageLabel:healthNumber(c.coverage)+'%',statusLabel:healthLabel(c.status)})));
async function load(){if(busy.value)return;busy.value=true;error.value='';category.value=null;check.value=null;try{const r=await request('/health-score');if(live)report.value=r;}catch(e){if(live)error.value=String(e);}finally{if(live)busy.value=false;}}
onMounted(()=>{load();timer=setInterval(()=>now.value=Date.now(),15000);});onUnmounted(()=>{live=false;clearInterval(timer);});
</script>
<template><div class="module-stack health-view"><section class="panel"><header><div><h2>{{t('Здоровье кластера')}}</h2><p>{{t('Последняя проверка')}}: {{certificateDate(report?.checkedAt)}}</p></div><div class="toolbar"><button :disabled="busy" @click="load">{{t('Обновить')}}</button><button @click="emit('diagnostics')">{{t('Диагностика')}}</button></div></header><p v-if="error" class="notice error" role="alert">{{error}} · {{t('Состояние не подтверждено. Повторите проверку.')}}</p><p v-if="busy&&!report" class="loading-state" role="status">{{t('Загрузка…')}}</p>
<template v-if="report"><p v-if="!report.snapshotId" class="notice" role="status">{{t('Нет данных о здоровье. Состояние не подтверждено.')}}</p><p v-else-if="stale" class="notice" role="status">{{t('Данные устарели. Оценка не подтверждает текущее состояние кластера.')}}</p><div class="summary-strip"><span>{{t('Оценка')}} <strong>{{error||stale||report.score===null?t('Недостаточно данных'):healthNumber(report.score)+' / 100'}}</strong></span><span>{{t('Покрытие проверками')}} <strong>{{healthNumber(report.coverage)}}%</strong></span><span v-if="report.observedScore!==null">{{t('По проверенным данным')}} <strong>{{healthNumber(report.observedScore)}} / 100</strong></span><span>{{t('Критично')}} <strong>{{critical.length}}</strong></span></div>
<p class="footnote">{{t('Политика')}} v{{report.policyVersion}} · {{t('Снимок')}} <code>{{report.snapshotId||'—'}}</code></p><p class="footnote">{{t('Оценка категории учитывает худшую проверку и указанные вычеты. Веса категорий заданы политикой; неизвестные проверки уменьшают покрытие. Кэш — 5 минут, данные старше 10 минут устаревают.')}}</p><p class="footnote">{{t('В политике v1 предупреждение вычитает 25 баллов, критическая проверка — 75, потеря кворума, истёкший или ещё не действующий сертификат — 100. Вычеты внутри категории не суммируются: применяется наибольший.')}} {{t('Категория сертификатов оценивает сроки и доверие, а не всю безопасность кластера.')}}</p>
<div v-if="critical.length" class="notice error" role="alert"><strong>{{t('Критические проблемы обнаружены')}}</strong><div v-for="finding in critical" :key="finding.id"><button @click="check=finding">{{finding.title||finding.id}}</button> · {{finding.node||finding.resource}}</div></div>
<ResourceTable :rows="rows" :columns="[{key:'label',title:t('Категория')},{key:'weight',title:t('Вес')},{key:'result',title:t('Оценка')},{key:'coverageLabel',title:t('Покрытие проверками')},{key:'statusLabel',title:t('Состояние')}]" :empty="t('Нет данных о здоровье. Состояние не подтверждено.')" @select="category=$event" /></template><p v-else-if="!busy&&!error" class="notice">{{t('Нет данных о здоровье. Состояние не подтверждено.')}}</p></section>
<section v-if="category" class="panel"><header><h2>{{healthLabel(category.id)}}</h2><button @click="category=null">{{t('Закрыть')}}</button></header><p class="footnote">{{t('Вес')}}: {{category.weight}} · {{t('Покрытие проверками')}}: {{category.coverage}}% · {{t('По проверенным данным')}}: {{healthNumber(category.observedScore)}}</p><ResourceTable :rows="(category.checks||[]).map(c=>({...c,stateLabel:healthLabel(c.state)}))" :columns="[{key:'title',title:t('Проверка')},{key:'id',title:'Check ID'},{key:'stateLabel',title:t('Состояние')},{key:'node',title:t('Нода')},{key:'reason',title:t('Причина')}]" @select="check=$event" /><h3>{{t('Вычеты категории')}}</h3><ResourceTable :search="false" :rows="category.deductions||[]" :columns="[{key:'checkId',title:'Check ID'},{key:'points',title:t('Баллы')},{key:'reason',title:t('Причина')}]" :empty="t('Нет вычетов. Проверяйте покрытие и неизвестные результаты.')" /></section>
<Modal v-if="check" :title="check.title||check.id" @close="check=null"><p :class="['notice',{'error':check.state==='critical'}]">{{healthLabel(check.state)}}</p><dl class="detail-grid"><dt>Check ID</dt><dd>{{check.id}}</dd><dt>{{t('Категория')}}</dt><dd>{{healthLabel(check.category)}}</dd><dt>{{t('Ресурс')}}</dt><dd>{{check.resource||'—'}}</dd><dt>{{t('Нода')}}</dt><dd>{{check.node||'—'}}</dd><dt>{{t('Последняя проверка')}}</dt><dd>{{certificateDate(check.observedAt)}}</dd><dt>{{t('Причина')}}</dt><dd>{{check.reason}}</dd></dl><p class="inspection-copy">{{check.details}}</p><p class="inspection-copy">{{check.suggestedAction}}</p><div class="toolbar"><button v-if="check.node" @click="emit('node',check.node);check=null">{{t('Открыть ноду')}}</button><button v-if="check.node" @click="emit('logs',check.node);check=null">{{t('Логи ноды')}}</button><button @click="emit('diagnostics');check=null">{{t('Диагностика')}}</button></div></Modal></div></template>
<style scoped>.health-view .footnote,.health-view code{overflow-wrap:anywhere;white-space:normal}.health-view .footnote,.health-view section>h3{margin:16px}.health-view .notice.error button{color:inherit}</style>
