<script setup lang="ts">
import { ref,computed,watch,onMounted,onUnmounted } from 'vue';
import { globalRequest,globalPost } from './client';import { t } from './i18n';import { isAdmin } from './permissions';import { notificationTime } from './notifications';
export interface ImageProfile {id:string;version:string;architecture:string;platform:string;extensions:{name:string;ref:string;digest:string}[];installerImage:string;isoURL:string;checkedAt:string}
const props=defineProps<{requireQemu?:boolean}>();const emit=defineEmits<{selected:[profile:ImageProfile|null]}>();
const versions=ref<string[]>([]),version=ref(''),extensions=ref<ImageProfile['extensions']>([]),chosen=ref<string[]>([]),profile=ref<ImageProfile|null>(null),existingID=ref(''),busy=ref(false),catalogBusy=ref(false),error=ref(''),stale=ref(false),versionsStale=ref(false),checkedAt=ref(''),query=ref(''),catalogReady=ref(false);let live=true,generation=0;
const qemu=computed(()=>extensions.value.find(e=>e.name==='qemu-guest-agent'||e.name.endsWith('/qemu-guest-agent'))?.name);
const allowed=computed(()=>!!version.value&&catalogReady.value&&!stale.value&&!versionsStale.value&&!catalogBusy.value&&!busy.value&&(!props.requireQemu||!!qemu.value&&chosen.value.includes(qemu.value)));
const visible=computed(()=>extensions.value.filter(e=>e.name.toLowerCase().includes(query.value.toLowerCase())));
function invalidate(){profile.value=null;emit('selected',null);}
async function loadVersions(){invalidate();versions.value=[];version.value='';extensions.value=[];chosen.value=[];error.value='';busy.value=true;try{const r=await globalRequest('/images/versions');if(live){versions.value=r.versions||[];versionsStale.value=!!r.stale;checkedAt.value=r.checkedAt||'';if(!versionsStale.value)version.value=versions.value[0]||'';}}catch(e){if(live)error.value=String(e);}finally{if(live)busy.value=false;}}
async function loadExtensions(){const id=++generation;invalidate();catalogReady.value=false;extensions.value=[];chosen.value=[];error.value='';stale.value=false;catalogBusy.value=false;if(!version.value)return;catalogBusy.value=true;try{const r=await globalRequest('/images/extensions?version='+encodeURIComponent(version.value));if(live&&id===generation){extensions.value=r.extensions||[];catalogReady.value=Array.isArray(r.extensions);stale.value=!!r.stale;checkedAt.value=r.checkedAt||'';if(props.requireQemu&&qemu.value&&!stale.value)chosen.value=[qemu.value];}}catch(e){if(live&&id===generation)error.value=String(e);}finally{if(live&&id===generation)catalogBusy.value=false;}}
watch(version,loadExtensions);watch(chosen,invalidate,{deep:true});watch(existingID,invalidate);
async function resolve(existing=false){if(!allowed.value)return;invalidate();error.value='';busy.value=true;const id=generation;try{const value=existing?await globalRequest('/images/schematics/'+encodeURIComponent(existingID.value.trim())+'?version='+encodeURIComponent(version.value)):await globalPost('/images/schematics',{version:version.value,architecture:'amd64',platform:'metal',extensions:chosen.value});if(live&&id===generation){if(props.requireQemu&&!value.extensions.some((e:any)=>e.name==='qemu-guest-agent'||e.name.endsWith('/qemu-guest-agent')))throw new Error(t('Для Proxmox требуется qemu-guest-agent.'));profile.value=value;emit('selected',value);}}catch(e){if(live&&id===generation){error.value=String(e);invalidate();}}finally{if(live)busy.value=false;}}
onMounted(loadVersions);onUnmounted(()=>{live=false;generation++;});
</script>
<template><section class="panel"><header><div><h2>{{ t('Образы Talos') }}</h2><p>amd64 · metal · {{ notificationTime(checkedAt) }}</p></div><button type="button" :disabled="busy||catalogBusy" @click="loadVersions">{{ t('Обновить каталог') }}</button></header><p v-if="error" class="notice error" role="alert">{{ error }}</p><p v-if="stale||versionsStale" class="notice warning">{{ t('Каталог устарел. Создание профиля заблокировано до успешного обновления.') }}</p><div class="settings-form"><label>{{ t('Версия Talos') }}<select v-model="version" :aria-label="t('Версия Talos')" :disabled="busy||catalogBusy||versionsStale"><option v-if="!versions.length" value="">{{ t('Каталог недоступен') }}</option><option v-for="item in versions" :key="item" :value="item">{{ item }}</option></select></label><div v-if="busy||catalogBusy" class="loading-state">{{ t('Загрузка…') }}</div><p v-if="requireQemu" class="footnote">{{ t('Для Proxmox требуется qemu-guest-agent. ISO и installer используют один schematic.') }}</p><p v-if="requireQemu&&version&&!catalogBusy&&!qemu" class="notice warning">{{ t('Для Proxmox требуется qemu-guest-agent.') }}</p><label>{{ t('Найти расширение') }}<input v-model="query" /></label><div class="image-extension-list"><label v-for="extension in visible" :key="extension.name"><input v-model="chosen" type="checkbox" :value="extension.name" :disabled="!isAdmin||busy||catalogBusy||stale||versionsStale||(requireQemu&&extension.name===qemu)" /> <span>{{ extension.name }}<small class="mono">{{ extension.ref }}</small></span></label><p v-if="!visible.length&&!catalogBusy" class="footnote">{{ t('Нет доступных расширений по выбранному фильтру') }}</p></div><button v-if="isAdmin" type="button" class="primary" :disabled="!allowed" @click="resolve()">{{ t('Создать профиль образа') }}</button><details><summary>{{ t('Открыть существующий schematic') }}</summary><label>Schematic ID<input v-model="existingID" maxlength="64" pattern="[a-f0-9]{64}" /></label><button type="button" :disabled="!allowed||!/^[a-f0-9]{64}$/.test(existingID)" @click="resolve(true)">{{ t('Проверить schematic') }}</button></details></div><section v-if="profile" class="surface"><header class="surface-heading"><h3>{{ t('Профиль образа') }}</h3><span>{{ profile.version }} · {{ profile.architecture }} / {{ profile.platform }}</span></header><dl class="detail-grid"><dt>Schematic ID</dt><dd class="mono">{{ profile.id }}</dd><dt>Installer</dt><dd class="mono">{{ profile.installerImage }}</dd><dt>ISO</dt><dd><a :href="profile.isoURL" target="_blank" rel="noopener noreferrer">{{ t('Скачать ISO из Image Factory') }}</a></dd><dt>{{ t('Расширения') }}</dt><dd>{{ profile.extensions.map(e=>e.name).join(', ')||t('Без расширений') }}</dd></dl><p class="footnote">{{ t('Создание профиля не меняет ноды. Применение образа требует плана provisioning или обновления.') }}</p></section></section></template>
