import {
  Activity,
  Server,
  Boxes,
  HardDrive,
  FileCode2,
  Database,
  Archive,
  Wrench,
  ScrollText,
  Settings,
  RefreshCw,
  Network,
  Shield,
  Search,
  Bell,
  Terminal,
  Cloud,
} from "lucide-vue-next";
import { t } from "./i18n";

export function navigation() {
  return [
    {
      id: "clusters",
      title: t("Кластеры"),
      icon: Network,
      group: t("ПЛАТФОРМА"),
      description: t("Все подключённые кластеры и их состояние."),
      global: true,
    },
    {
      id: "providers",
      hidden: true,
      title: t("Провайдеры"),
      icon: Cloud,
      group: t("ПЛАТФОРМА"),
      description: t(
        "Подключения к инфраструктуре для создания машин и кластеров.",
      ),
      global: true,
    },
    {
      id: "users",
      hidden: true,
      title: t("Доступ"),
      icon: Shield,
      group: t("ПЛАТФОРМА"),
      description: t("Пользователи, роли и единый вход."),
      global: true,
    },
    {id:'global-audit',title:t('Аудит платформы'),icon:ScrollText,group:t('ПЛАТФОРМА'),description:t('Подключения, провайдеры, пользователи и операции платформы.'),global:true},
    {id:'fleet-machines',title:t('Ресурсы провайдеров'),icon:Boxes,group:t('ПЛАТФОРМА'),description:t('Машины TalosDeck и ресурсы незавершённых операций.'),global:true},
    {id:'templates',title:t('Шаблоны кластеров'),icon:Boxes,group:t('ПЛАТФОРМА'),description:t('Повторяемые конфигурации и неизменяемые ревизии кластеров.'),global:true},
    {id:'images',title:t('Образы Talos'),icon:Archive,group:t('ПЛАТФОРМА'),description:t('Image Factory: версии, расширения и воспроизводимые образы.'),global:true},
    {id:'platform-settings',title:t('Настройки платформы'),icon:Settings,group:t('ПЛАТФОРМА'),description:t('Подключения, пользователи и доступ к платформе.'),global:true},
    {
      id: "overview",
      title: t("Обзор"),
      icon: Activity,
      group: t("КЛАСТЕР"),
      description: t("Доступность, ресурсы и состояние инфраструктуры."),
    },
    {
      id: "nodes",
      title: t("Ноды"),
      icon: Server,
      group: t("ИНФРАСТРУКТУРА"),
      description: t(
        "Машины Talos Linux. Выберите ноду для просмотра сервисов и логов.",
      ),
    },
    {
      id: "machines",
      title: t("Виртуальные машины"),
      icon: Boxes,
      group: t("ИНФРАСТРУКТУРА"),
      description: t("Машины, созданные TalosDeck для этого кластера."),
    },
    {
      id: "storage",
      title: t("Хранилище"),
      icon: HardDrive,
      group: t("ИНФРАСТРУКТУРА"),
      description: t("Диски, разделы и точки монтирования на каждой машине."),
    },
    {
      id: "workloads",
      title: t("Рабочие нагрузки"),
      icon: Boxes,
      group: "KUBERNETES",
      description: t("Поды Kubernetes во всех пространствах имён."),
    },
    {
      id: "events",
      title: t("События"),
      icon: ScrollText,
      group: "KUBERNETES",
      description: t(
        "События Kubernetes для диагностики нод и рабочих нагрузок.",
      ),
    },
    {
      id: "kube-storage",
      title: t("Тома"),
      icon: HardDrive,
      group: "KUBERNETES",
      description: t(
        "Persistent volumes, claims и классы хранения Kubernetes.",
      ),
    },
    {
      id: "jobs",
      title: t("Задания"),
      icon: ScrollText,
      group: t("ОПЕРАЦИИ"),
      description: t("Фоновые операции, состояние шагов и журнал выполнения."),
    },
    {id:"worker-replacement",title:t("Замена worker"),icon:Wrench,group:t("ОПЕРАЦИИ"),description:t("Замена зарегистрированной worker-машины с проверкой данных и fencing.")},
    {
      id: "updates",
      title: t("Обновления"),
      icon: RefreshCw,
      group: t("ОПЕРАЦИИ"),
      description: t("Проверка и обновление Talos Linux и Kubernetes."),
    },
    {
      id: "backups",
      title: t("Резервные копии"),
      icon: Archive,
      group: t("ОПЕРАЦИИ"),
      description: t("Снимки, расписание и восстановление состояния кластера."),
    },
    {
      id: "maintenance",
      title: t("Обслуживание"),
      icon: Wrench,
      group: t("ОПЕРАЦИИ"),
      description: t(
        "Безопасное обслуживание и последовательная перезагрузка нод.",
      ),
    },
    {id:'alert-center',title:t('Оповещения'),icon:Bell,group:t('НАБЛЮДЕНИЕ'),description:t('Активные и устранённые проблемы, приостановки и доставка.')},
    {
      id: "health",
      title: t("Здоровье"), icon:Activity, group:t("НАБЛЮДЕНИЕ"), description:t("Оценка, покрытие и доказательства состояния кластера."),
    },
    {
      id: "diagnostics",
      title: t("Диагностика"),
      icon: Search,
      group: t("НАБЛЮДЕНИЕ"),
      description: t("Проверки здоровья и рекомендации по устранению проблем."),
    },
    { id: "certificates", title: t("Сертификаты"), icon: Shield, group: t("НАБЛЮДЕНИЕ"), description: t("Сроки действия credentials и проверка TLS endpoints.") },
    {
      id: "etcd",
      title: "etcd",
      icon: Database,
      group: t("НАБЛЮДЕНИЕ"),
      description: t(
        "Участники, лидер и состояние распределённой базы данных.",
      ),
    },
    {
      id: "logs",
      title: t("Логи"),
      icon: Terminal,
      group: t("НАБЛЮДЕНИЕ"),
      description: t("Потоковые логи Talos без SSH."),
    },
    {
      id: "alerts",
      hidden: true,
      title: t("Уведомления"),
      icon: Bell,
      group: t("НАСТРОЙКИ КЛАСТЕРА"),
      description: t("Условия оповещений и каналы доставки для кластера."),
    },
    {id:'cluster-settings',title:t('Настройки кластера'),icon:Settings,group:t('НАСТРОЙКИ КЛАСТЕРА'),description:t('Подключение, MachineConfig и уведомления.')},
    {
      id: "config",
      hidden: true,
      title: t("Конфигурация"),
      icon: FileCode2,
      group: t("НАСТРОЙКИ КЛАСТЕРА"),
      description: t("MachineConfig: изменения, сравнение и история ревизий."),
    },
    {
      id: "audit",
      title: t("Аудит"),
      icon: ScrollText,
      group: t("ОПЕРАЦИИ"),
      description: t("История действий и результаты операций."),
    },
    {
      id: "settings",
      hidden: true,
      title: t("Подключение"),
      icon: Settings,
      group: t("НАСТРОЙКИ КЛАСТЕРА"),
      description: t("Подключение к кластеру и параметры консоли."),
    },
  ];
}
