<script setup lang="ts">
import { ref,computed,onMounted,onUnmounted } from 'vue';import { request,post } from './client';import { t } from './i18n';import { type NotificationChannel,type NotificationRoute } from './notifications';import ResourceTable from './ResourceTable.vue';import Modal from './Modal.vue';import DeliveryHistory from './DeliveryHistory.vue';
const channels=ref<NotificationChannel[]>([]),routes=ref<NotificationRoute[]>([]),revision=ref(0),tab=ref('channels'),busy=ref(false),error=ref(''),notice=ref(''),editing=ref(false),replace=ref(false),confirm=ref<{kind:'test'|'delete';channel:Pick<NotificationChannel,'id'|'name'>}|null>(null),routeOpen=ref(false);
const channelType=(kind:string)=>({telegram:'Telegram',slack:'Slack',webhook:'Webhook',discord:'Discord',email:'Email'} as Record<string,string>)[kind]||kind;
const blank=()=>({id:'',name:'',type:'telegram',recipientUser:'',enabled:true,generation:0,config:{} as Record<string,string>});const form=ref(blank());
const blankRoute=():NotificationRoute=>({id:'',name:'',enabled:true,minSeverity:'warning',ruleIds:[],nodeIds:[],channelIds:[],sendResolved:true,repeatMinutes:0});const routeForm=ref(blankRoute()),ruleText=ref(''),nodeText=ref('');let live=true;
const fields=computed(()=>({telegram:[['token','Bot token','password'],['chatId','Chat ID','text']],slack:[['url','Webhook URL','password']],discord:[['url','Webhook URL','password']],webhook:[['url','Webhook URL','text'],['hmacSecret','HMAC secret','password']],email:[['smtpHost','SMTP host','text'],['smtpPort','SMTP port','number'],['smtpUsername','SMTP username','text'],['smtpPassword','SMTP password','password'],['smtpFrom','From','email'],['smtpTo',t('Получатели через запятую'),'text']]} as Record<string,string[][]>)[form.value.type]||[]);
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){if(live)error.value=e instanceof Error?e.message:String(e);}finally{if(live)busy.value=false;}}
async function load(){await run(async()=>{const [c,r]=await Promise.all([request('/notifications/channels'),request('/notifications/routes')]);if(live){channels.value=c.channels||[];routes.value=r.routes||[];revision.value=r.revision;}});}
function edit(channel?:NotificationChannel){form.value=channel?{...channel,recipientUser:channel.recipientUser||'',config:{}}:blank();replace.value=!channel;editing.value=true;}
function close(){if(busy.value)return;editing.value=false;form.value=blank();}
async function save(){await run(async()=>{const {id,name,type,recipientUser,enabled,generation}=form.value;const body={id,name,type,recipientUser,enabled,generation,config:replace.value?form.value.config:{}};await request('/notifications/channels'+(form.value.id?'/'+form.value.id:''),{method:form.value.id?'PUT':'POST',body:JSON.stringify(body)});if(live){editing.value=false;form.value=blank();}});if(!error.value)await load();}
async function confirmChannel(){const action=confirm.value;if(!action)return;await run(async()=>{if(action.kind==='test')await post('/notifications/channels/'+action.channel.id+'/test',{});else await request('/notifications/channels/'+action.channel.id,{method:'DELETE'});if(live){confirm.value=null;editing.value=false;form.value=blank();notice.value=action.kind==='test'?t('Тест поставлен в очередь. Результат смотрите в истории доставки.'):t('Канал удалён');}});if(!error.value&&action.kind==='delete')await load();}
function editRoute(value?:NotificationRoute){routeForm.value=value?JSON.parse(JSON.stringify(value)):blankRoute();ruleText.value=(routeForm.value.ruleIds||[]).join(', ');nodeText.value=(routeForm.value.nodeIds||[]).join(', ');routeOpen.value=true;}
async function saveRoute(remove=false){await run(async()=>{const {id,name,enabled,minSeverity,channelIds,sendResolved,repeatMinutes}=routeForm.value;const value={id,name,enabled,minSeverity,channelIds,sendResolved,repeatMinutes,ruleIds:ruleText.value.split(',').map(s=>s.trim()).filter(Boolean),nodeIds:nodeText.value.split(',').map(s=>s.trim()).filter(Boolean)};const next=routes.value.filter(r=>r.id!==value.id);if(!remove)next.push(value);await request('/notifications/routes',{method:'PUT',body:JSON.stringify({revision:revision.value,routes:next})});if(live)routeOpen.value=false;});if(!error.value)await load();}
onMounted(load);onUnmounted(()=>{live=false;form.value=blank();});
</script>
<template><section class="panel"><header><h2>{{ t('Доставка уведомлений') }}</h2><button :disabled="busy" @click="load">{{ t('Обновить') }}</button></header><nav class="section-tabs"><button @click="tab='channels'">{{ t('Каналы') }}</button><button @click="tab='routes'">{{ t('Маршруты') }}</button><button @click="tab='deliveries'">{{ t('История доставки') }}</button></nav><p v-if="error" class="notice error" role="alert">{{ error }}</p><p v-if="notice" class="notice" role="status">{{ notice }}</p><DeliveryHistory v-if="tab==='deliveries'" /><template v-else-if="tab==='channels'"><div class="toolbar"><button class="primary" @click="edit()">{{ t('Добавить канал') }}</button></div><p class="footnote">{{ t('Credentials хранятся на сервере. Сохранение канала не отправляет тестовое сообщение.') }}</p><div v-if="busy&&!channels.length" class="loading-state">{{ t('Загрузка…') }}</div><ResourceTable v-else :rows="channels.map(c=>({...c,typeLabel:channelType(c.type),enabledLabel:t(c.enabled?'Да':'Нет'),configuredLabel:t(c.configured?'Да':'Нет')}))" :columns="[{key:'name',title:t('Имя')},{key:'typeLabel',title:t('Тип')},{key:'enabledLabel',title:t('Включён')},{key:'configuredLabel',title:t('Настроен')},{key:'recipientUser',title:t('Получатель-пользователь')}]" @select="edit($event)" /></template><template v-else><div class="toolbar"><button class="primary" @click="editRoute()">{{ t('Добавить маршрут') }}</button></div><p class="footnote">{{ t('Маршруты относятся к выбранному кластеру. Получатели задаются каналами.') }}</p><ResourceTable :rows="routes.map(r=>({...r,enabledLabel:t(r.enabled?'Да':'Нет'),resolvedLabel:t(r.sendResolved?'Да':'Нет')}))" :columns="[{key:'name',title:t('Имя')},{key:'enabledLabel',title:t('Включён')},{key:'minSeverity',title:t('Минимальный уровень')},{key:'channelIds',title:t('Каналы')},{key:'resolvedLabel',title:t('Отправлять устранение')}]" @select="editRoute($event)" /></template></section>
<Modal v-if="editing" :title="form.id?t('Настройки канала'):t('Добавить канал')" @close="close"><form class="settings-form" @submit.prevent="save"><label>{{ t('Имя') }}<input v-model="form.name" required maxlength="100" /></label><label>{{ t('Тип') }}<select :aria-label="t('Тип канала')" v-model="form.type" :disabled="!!form.id" @change="form.config={}"><option v-for="kind in ['telegram','slack','webhook','discord','email']" :key="kind" :value="kind">{{ channelType(kind) }}</option></select></label><label>{{ t('Получатель-пользователь') }}<input v-model="form.recipientUser" autocomplete="off" /></label><label><input v-model="form.enabled" type="checkbox" /> {{ t('Включён') }}</label><label v-if="form.id"><input v-model="replace" type="checkbox" @change="form.config={}" /> {{ t('Заменить credentials целиком') }}</label><template v-if="replace"><p v-if="form.id" class="notice warning">{{ t('Введите полный новый набор. Пустые поля не копируются из сохранённых credentials.') }}</p><label v-for="[key,label,type] in fields" :key="key">{{ label }}<input v-model="form.config[key]" :type="type" autocomplete="new-password" :required="!['smtpUsername','smtpPassword','hmacSecret'].includes(key)" /></label><label v-if="form.type==='email'">SMTP TLS<select v-model="form.config.smtpTLS" required><option value="tls">TLS</option><option value="starttls">STARTTLS</option></select></label><label v-if="form.type==='webhook'"><input type="checkbox" :checked="form.config.allowHTTP==='true'" @change="form.config.allowHTTP=($event.target as HTMLInputElement).checked?'true':'false'" /> {{ t('Разрешить HTTP без TLS для этого webhook') }}</label></template><p v-else class="footnote">{{ t('Сохранённые credentials остаются без изменений.') }}</p><p v-if="error" class="notice error" role="alert">{{ error }}</p><div class="toolbar"><button class="primary" :disabled="busy">{{ t('Сохранить') }}</button><button v-if="form.id" type="button" :disabled="busy" @click="confirm={kind:'test',channel:{id:form.id,name:form.name}}">{{ t('Отправить тест') }}</button><button v-if="form.id" type="button" :disabled="busy" @click="confirm={kind:'delete',channel:{id:form.id,name:form.name}}">{{ t('Удалить канал') }}</button></div></form></Modal>
<Modal v-if="confirm" :title="confirm.kind==='test'?t('Отправить тест'):t('Удалить канал')" @close="confirm=null"><p>{{ confirm.channel.name }}</p><p>{{ confirm.kind==='test'?t('Будет отправлено реальное сообщение получателю сохранённого канала.'):t('Удаление отключит этот канал. Проверьте использующие его маршруты.') }}</p><p v-if="error" class="notice error">{{ error }}</p><button :disabled="busy" @click="confirmChannel">{{ t('Подтвердить') }}</button></Modal>
<Modal v-if="routeOpen" :title="t('Маршрут уведомлений')" @close="routeOpen=false"><form class="settings-form" @submit.prevent="saveRoute()"><label>{{ t('Имя') }}<input v-model="routeForm.name" required /></label><label><input v-model="routeForm.enabled" type="checkbox" /> {{ t('Включён') }}</label><label>{{ t('Минимальный уровень') }}<select v-model="routeForm.minSeverity"><option>info</option><option>warning</option><option>critical</option></select></label><fieldset><legend>{{ t('Каналы') }}</legend><label v-for="channel in channels" :key="channel.id"><input v-model="routeForm.channelIds" type="checkbox" :value="channel.id" /> {{ channel.name }} · {{ channel.type }}</label></fieldset><label>{{ t('Правила через запятую, пусто — все') }}<input v-model="ruleText" /></label><label>{{ t('Ноды через запятую, пусто — все') }}<input v-model="nodeText" /></label><label><input v-model="routeForm.sendResolved" type="checkbox" /> {{ t('Отправлять устранение') }}</label><label>{{ t('Повтор, минуты; 0 — отключён') }}<input v-model.number="routeForm.repeatMinutes" type="number" min="0" /></label><p v-if="error" class="notice error" role="alert">{{ error }}</p><button class="primary" :disabled="busy||!routeForm.channelIds.length">{{ t('Сохранить маршрут') }}</button><button v-if="routeForm.id" type="button" :disabled="busy" @click="saveRoute(true)">{{ t('Удалить маршрут') }}</button></form></Modal>
</template>
