import { t, locale } from './i18n';
export interface AlertRecord { id:string; clusterId:string; fingerprint:string;ruleId:string;resourceId:string;node?:string;component:string;severity:string;state:string;title:string;details:string;suggestedAction?:string;firstSeen:string;lastSeen:string;lastChanged:string;resolvedAt?:string;occurrences:number;transition:number;event?:boolean;observation:string;silencedUntil?:string }
export interface AlertSnapshot {alerts:AlertRecord[];summary:{active:number;critical:number;warning:number;silenced:number;stale:number};health:string;lastCheckAt:string}
export interface Silence {id:string;ruleId?:string;node?:string;severity?:string;startsAt:string;endsAt:string;reason:string;createdBy:string;createdAt:string}
export interface NotificationChannel {id:string;name:string;type:string;recipientUser?:string;enabled:boolean;configured:boolean;generation:number;createdAt:string;updatedAt:string}
export interface NotificationRoute {id:string;name:string;enabled:boolean;minSeverity:string;ruleIds:string[];nodeIds:string[];channelIds:string[];sendResolved:boolean;repeatMinutes:number}
export interface NotificationDelivery {id:string;alertId:string;transition:number;channelId:string;channelGeneration:number;state:string;attempts:number;nextAttemptAt:string;createdAt:string;lastAttemptAt?:string;deliveredAt?:string;errorCode?:string}
export function notificationTime(value?:string) {if(!value||!Number.isFinite(Date.parse(value))||value.startsWith('0001-'))return '—';return new Date(value).toLocaleString(locale.value==='ru'?'ru-RU':'en-GB');}
export function notificationDuration(start:string,end?:string) {const value=Math.max(0,Math.floor(((end?Date.parse(end):Date.now())-Date.parse(start))/60000));if(!Number.isFinite(value))return '—';return value<60?t('{0} мин.',[value]):value<1440?t('{0} ч.',[Math.floor(value/60)]):t('{0} дн.',[Math.floor(value/1440)]);}
export function notificationLabel(value:string) {return t(({active:'Активно',resolved:'Устранено',critical:'Критический',warning:'Предупреждение',info:'Информация',unknown:'Неизвестно',stale:'Устарело',known:'Подтверждено',healthy:'Исправен',degraded:'Деградирован',pending:'В очереди',queued:'В очереди',sending:'Отправляется',sent:'Доставлено',retrying:'Повторная попытка',suppressed:'Подавлено',failed:'Ошибка доставки',uncertain:'Доставка не подтверждена',cancelled:'Отменено'} as Record<string,string>)[String(value).toLowerCase()]||value);}
