<script setup lang="ts">
import {ref,computed,watch,onMounted,onUnmounted} from 'vue';
import {globalRequest,globalPost} from './client';import {isAdmin} from './permissions';import {t} from './i18n';import ResourceTable from './ResourceTable.vue';import ImagePicker,{type ImageProfile} from './ImagePicker.vue';
const emit=defineEmits<{submitted:[any]}>();
const templates=ref<any[]>([]),revisions=ref<any[]>([]),selected=ref<any>(null),revision=ref<any>(null),providers=ref<any[]>([]),busy=ref(false),error=ref(''),archived=ref(false),editing=ref(false),instantiating=ref(false),plan=ref<any>(null),confirmed=ref(''),name=ref(''),imageReady=ref(false),showPicker=ref(false),editExpectedRevision=ref(0);
const defaults=()=>({cores:4,memoryMB:4096,diskGB:40,storage:'',bridge:'',vlan:0,networkMode:'dhcp'});
const fresh=()=>({talosVersion:'',kubernetesVersion:'',schematicId:'',architecture:'amd64',platform:'metal',cni:'flannel',storage:'none',controlPlanes:1,workers:1,controlPlane:defaults(),worker:defaults()});
const spec=ref<any>(fresh()),runtime=ref<any>({name:'',providerId:'',isoStorage:'',endpoint:'',machines:[]});let live=true;
const shown=computed(()=>templates.value.filter(x=>archived.value||!x.archived).map(x=>({...x,state:x.archived?t('В архиве'):t('Активен')})));
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){if(live)error.value=String(e);}finally{if(live)busy.value=false;}}
async function load(){await run(async()=>{const r=await globalRequest('/templates?archived=true');if(live){templates.value=r.templates||[];if(selected.value)selected.value=templates.value.find(x=>x.id===selected.value.id)||null;}});}
async function select(row:any){if(busy.value)return;editing.value=false;instantiating.value=false;plan.value=null;confirmed.value='';selected.value=row;revision.value=null;revisions.value=[];await run(async()=>{const r=await globalRequest('/templates/'+row.id+'/revisions');if(live){revisions.value=r.revisions||[];revision.value=revisions.value.find(x=>x.revision===row.latestRevision)||revisions.value[0];}});}
function edit(create=false){editExpectedRevision.value=selected.value?.latestRevision||0;showPicker.value=create;editing.value=true;instantiating.value=false;plan.value=null;imageReady.value=!create;name.value=create?'':revision.value.name;spec.value=create?fresh():JSON.parse(JSON.stringify(revision.value.spec));if(create){selected.value=null;revision.value=null;revisions.value=[];}}
function image(p:ImageProfile|null){imageReady.value=!!p;spec.value.schematicId=p?.id||'';spec.value.talosVersion=p?.version||'';}
async function save(){await run(async()=>{const r=await globalPost(selected.value?'/templates/'+selected.value.id+'/revisions':'/templates',{name:name.value,spec:spec.value,...(selected.value?{expectedRevision:editExpectedRevision.value}:{})});if(live){editing.value=false;const list=await globalRequest('/templates?archived=true');templates.value=list.templates||[];selected.value=templates.value.find(x=>x.id===r.templateId);revisions.value=[r];revision.value=r;}});}
async function archive(){await run(async()=>{await globalRequest('/templates/'+selected.value.id+'/archive',{method:'PUT',body:JSON.stringify({expectedRevision:selected.value.latestRevision,archived:!selected.value.archived})});if(live){selected.value.archived=!selected.value.archived;templates.value=templates.value.map(x=>x.id===selected.value.id?{...x,archived:selected.value.archived}:x);plan.value=null;instantiating.value=false;}});}
async function instantiate(){plan.value=null;confirmed.value='';editing.value=false;instantiating.value=true;runtime.value={name:'',providerId:'',isoStorage:'',endpoint:'',machines:[]};const s=revision.value.spec;for(const role of ['controlplane','worker'])for(let i=0;i<(role==='controlplane'?s.controlPlanes:s.workers);i++)runtime.value.machines.push({name:(role==='controlplane'?'cp':'worker')+'-'+(i+1),role,address:'',gateway:'',nameservers:[]});await run(async()=>{const r=await globalRequest('/providers');if(live){providers.value=Array.isArray(r)?r:r.providers||[];runtime.value.providerId=providers.value[0]?.id||'';}});}
watch(runtime,()=>{plan.value=null;confirmed.value='';},{deep:true});
function chooseRevision(event:Event){revision.value=revisions.value.find(x=>x.revision===Number((event.target as HTMLSelectElement).value));editing.value=false;instantiating.value=false;plan.value=null;confirmed.value='';}
async function preview(){await run(async()=>{const r=await globalPost(`/templates/${selected.value.id}/revisions/${revision.value.revision}/plans`,runtime.value);if(live)plan.value=r;});}
async function submit(){if(!plan.value||confirmed.value!==plan.value.spec.name)return;await run(async()=>{const job=await globalPost('/provision',{planId:plan.value.id,confirmedName:confirmed.value});if(live){plan.value=null;emit('submitted',job);}});}
onMounted(load);onUnmounted(()=>live=false);
</script>
<template><div class="module-stack templates-view">
<p v-if="error" class="notice error" role="alert">{{error}} <span>{{t('При конфликте перечитайте каталог и проверьте последнюю ревизию перед повторной записью.')}}</span></p>
<section class="panel"><header><h2>{{t('Шаблоны кластеров')}}</h2><div class="toolbar"><label><input type="checkbox" v-model="archived" />{{t('Показать архив')}}</label><button :disabled="busy" @click="load">{{t('Обновить')}}</button><button v-if="isAdmin" :disabled="busy" @click="edit(true)">{{t('Новый шаблон')}}</button></div></header>
<p v-if="busy" class="footnote" role="status">{{t('Загрузка…')}}</p><ResourceTable :rows="shown" :columns="[{key:'name',title:t('Имя')},{key:'latestRevision',title:t('Ревизия')},{key:'state',title:t('Состояние')}]" :empty="t('Шаблонов пока нет. Создайте повторяемую конфигурацию кластера.')" @select="select" /></section>
<section v-if="revision && !editing" class="panel"><header><h2>{{revision.name}}</h2><div class="toolbar"><label>{{t('Ревизия')}}<select :aria-label="t('Ревизия')" :value="revision.revision" :disabled="busy" @change="chooseRevision"><option v-for="r in revisions" :value="r.revision" :key="r.revision">#{{r.revision}}</option></select></label><template v-if="isAdmin"><button :disabled="busy||selected.archived" @click="edit()">{{t('Новая ревизия')}}</button><button :disabled="busy" @click="archive">{{selected.archived?t('Вернуть из архива'):t('В архив')}}</button><button :disabled="busy||selected.archived" @click="instantiate">{{t('Создать из шаблона')}}</button></template></div></header>
<p class="footnote">{{revision.createdBy}} · {{revision.createdAt}} · <code>{{revision.specHash}}</code></p><dl class="detail-grid"><dt>Talos / Kubernetes</dt><dd>{{revision.spec.talosVersion}} / {{revision.spec.kubernetesVersion}}</dd><dt>{{t('Образ')}}</dt><dd><code>{{revision.spec.schematicId}}</code></dd><dt>CNI / Storage</dt><dd>{{revision.spec.cni}} / {{revision.spec.storage}}</dd><dt>Control plane / Workers</dt><dd>{{revision.spec.controlPlanes}} / {{revision.spec.workers}}</dd></dl>
<ResourceTable :search="false" :rows="[{role:'controlplane',...revision.spec.controlPlane},{role:'worker',...revision.spec.worker}]" :columns="[{key:'role',title:t('Роль')},{key:'cores',title:'CPU'},{key:'memoryMB',title:'RAM MB'},{key:'diskGB',title:'Disk GB'},{key:'storage',title:t('Хранилище')},{key:'bridge',title:'Bridge'},{key:'networkMode',title:t('Сеть')}]" /></section>
<form v-if="editing&&isAdmin" class="settings-form panel" @submit.prevent="save"><fieldset :disabled="busy"><h2>{{selected?t('Новая ревизия'):t('Новый шаблон')}}</h2><label>{{t('Имя шаблона')}}<input v-model="name" required /></label><p v-if="spec.schematicId" class="footnote">Talos {{spec.talosVersion}} · {{spec.schematicId}}</p><button type="button" @click="showPicker=!showPicker">{{t('Выбрать образ Talos')}}</button><ImagePicker v-if="showPicker" require-qemu @selected="image" /><div class="form-grid"><label>Kubernetes<input v-model="spec.kubernetesVersion" required /></label><label>Control plane<select v-model.number="spec.controlPlanes"><option :value="1">1</option><option :value="3">3</option></select></label><label>Workers<input v-model.number="spec.workers" type="number" min="0" max="100" required /></label><label>CNI<select v-model="spec.cni"><option>flannel</option><option>cilium</option></select></label><label>Storage<select v-model="spec.storage"><option>none</option><option>local-path</option></select></label></div>
<section v-for="role in ['controlPlane','worker']" :key="role"><h3>{{role==='controlPlane'?'Control plane':'Workers'}}</h3><div class="form-grid"><label>CPU<input v-model.number="spec[role].cores" type="number" min="1" required /></label><label>RAM MB<input v-model.number="spec[role].memoryMB" type="number" min="2048" required /></label><label>Disk GB<input v-model.number="spec[role].diskGB" type="number" min="10" required /></label><label>{{t('Хранилище')}}<input v-model="spec[role].storage" required /></label><label>Bridge<input v-model="spec[role].bridge" required /></label><label>VLAN<input v-model.number="spec[role].vlan" type="number" min="0" max="4094" /></label><label>{{t('Сеть')}}<select v-model="spec[role].networkMode"><option>dhcp</option><option>static</option></select></label></div></section><button :disabled="!imageReady||!spec.schematicId">{{t('Сохранить ревизию')}}</button><button type="button" @click="editing=false">{{t('Отмена')}}</button></fieldset></form>
<form v-if="instantiating&&isAdmin" class="settings-form panel" @submit.prevent="preview"><fieldset :disabled="busy"><h2>{{t('Создать из шаблона')}}: {{revision.name}} #{{revision.revision}}</h2><p class="footnote">{{t('Ресурсы и образ закреплены выбранной ревизией. Здесь задаются только параметры новой установки.')}}</p><div class="form-grid"><label>{{t('Имя кластера')}}<input v-model="runtime.name" required /></label><label>{{t('Провайдер')}}<select v-model="runtime.providerId" required><option v-for="p in providers" :value="p.id" :key="p.id">{{p.name}}</option></select></label><label>{{t('Хранилище ISO в Proxmox')}}<input v-model="runtime.isoStorage" required /></label><label>Endpoint<input v-model="runtime.endpoint" placeholder="https://10.0.0.10:6443" /></label></div><section v-for="(machine,index) in runtime.machines" :key="index"><h3>{{machine.role}} {{Number(index)+1}}</h3><div class="form-grid"><label>{{t('Имя ноды')}}<input v-model="machine.name" required /></label><template v-if="revision.spec[machine.role==='controlplane'?'controlPlane':'worker'].networkMode==='static'"><label>Address / CIDR<input v-model="machine.address" required /></label><label>Gateway<input v-model="machine.gateway" required /></label><label>DNS<input :value="machine.nameservers.join(', ')" @input="machine.nameservers=($event.target as HTMLInputElement).value.split(',').map(s=>s.trim()).filter(Boolean)" required /></label></template></div></section><button>{{t('Предпросмотр плана')}}</button></fieldset></form>
<section v-if="plan" class="panel"><header><h2>{{t('План создания')}}</h2></header><p>{{plan.template?.name}} #{{plan.template?.revision}} · <code>{{plan.template?.specHash}}</code></p><p v-for="note in plan.safetyNotes" :key="note" class="notice">{{note}}</p><ResourceTable :rows="plan.spec.machines" :search="false" :columns="[{key:'name',title:t('Имя')},{key:'role',title:t('Роль')},{key:'cores',title:'CPU'},{key:'memoryMB',title:'RAM MB'},{key:'diskGB',title:'Disk GB'}]" /><form class="settings-form" @submit.prevent="submit"><label>{{t('Введите имя кластера для подтверждения')}}<input v-model="confirmed" :disabled="busy" :placeholder="plan.spec.name" /></label><button class="primary" :disabled="busy||confirmed!==plan.spec.name">{{t('Создать кластер')}}</button></form></section>
</div></template>

<style scoped>
.templates-view .footnote, .templates-view code {overflow-wrap:anywhere;white-space:normal;}
.templates-view > .panel > .detail-grid, .templates-view > .panel > p {margin:16px;}
.templates-view > form.panel {padding:16px;}
</style>
